# Site settings
title: 3DPrinting
description: "Documentation of my 3D printing and modding process"
url: "https://PeterXQC.github.io"
baseurl: "/3DPrinting"     # <-- required for a repo at PeterXQC.github.io/3DPrinting

# Use Just the Docs as a remote theme on GitHub Pages
remote_theme: pmarsceill/just-the-docs   # <-- pulls theme from GitHub  
plugins:
  - jekyll-remote-theme                  # <-- enable remote_theme support
  - jekyll-feed
  - jemoji

# Just the Docs configuration
color_scheme: dark
callouts_level: loud
callouts:
  prereqs:
    title: Prerequisites
    color: yellow
  compat:
    title: Compatibility
    color: pink
  warning:
    title: Warning
    color: red
  attention:
    color: orange
  note:
    title: Note
    color: blue

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Find me":
    - "https://github.com/PeterXQC/3DPrinting"
