# Site settings
title: 3DPrinting
description: "Documentation of my 3D printing and modding process"
url: "https://PeterXQC.github.io"
baseurl: "/3DPrinting"     # <-- required for a repo at PeterXQC.github.io/3DPrinting

theme: just-the-docs   # <-- pulls theme from GitHub  
# plugins:
  
color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Find me":
    - "https://github.com/PeterXQC/3DPrinting"


