# Site settings
title: 3DPrinting
description: "Documentation of my 3D printing and modding process"
url: "https://PeterXQC.github.io"
baseurl: "/3DPrinting"     # <-- required for a repo at PeterXQC.github.io/3DPrinting

theme: just-the-docs   # <-- pulls theme from GitHub  
# plugins:
  
color_scheme: dark
# logo replaces title.
# logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/logo.png"
mermaid:
  version: "9.1.3"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Find me":
    - "https://github.com/PeterXQC/3DPrinting/issues"


