layout: default
title: 3DPrinting
email: qichenxu0724@gmail.com
github_username:  PeterXQC
github: [metadata]
url: https://PeterXQC.github.io/3DPrinting

# Build settings
theme: just-the-docs
color_scheme: dark

plugins:
  - jekyll-feed
  - jemoji

callouts_level: loud
callouts:
  prereqs:
    title: Prerequisites
    color: yellow
  compat:
    title: Compatibility
    color: pink
  warning:
    title: Warning
    color: red
  attention:
    color: orange
  note:
    title: Note
    color: blue

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Find me":
    - "https://github.com/PeterXQC/3DPrinting"